-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."group" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.member_list DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.member_list DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.join_request DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.join_request DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.favourite_movies DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.favourite_movies DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.review DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.review DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public.account;

CREATE TABLE IF NOT EXISTS public.account
(
    id serial NOT NULL,
    username character varying(16) NOT NULL,
    email character varying(64) NOT NULL,
    password character varying(64) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (id),
	UNIQUE (username)
);

-- Trigger function to make sure username and email will always be lowercased.
CREATE OR REPLACE FUNCTION lowercase_username_email()
RETURNS TRIGGER AS $$
BEGIN
    NEW.username := LOWER(NEW.username);
    NEW.email := LOWER(NEW.email);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger
CREATE TRIGGER trigger_lowercase_username_email
    BEFORE INSERT OR UPDATE ON public.account
    FOR EACH ROW
    EXECUTE FUNCTION lowercase_username_email();


DROP TABLE IF EXISTS public."group";

CREATE TABLE IF NOT EXISTS public."group"
(
    id serial NOT NULL,
    id_owner integer NOT NULL,
    group_name character varying(64) NOT NULL,
    group_descr character varying(255),
    creation_date timestamp with time zone NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (group_name, id_owner)
);

COMMENT ON TABLE public."group"
    IS 'Users can create different groups';

DROP TABLE IF EXISTS public.member_list;

CREATE TABLE IF NOT EXISTS public.member_list
(
    id_group integer NOT NULL,
    id_account integer NOT NULL,
    join_date timestamp with time zone,
    PRIMARY KEY (id_account, id_group)
);

DROP TABLE IF EXISTS public.join_request;

CREATE TABLE IF NOT EXISTS public.join_request
(
    id_group integer NOT NULL,
    id_account integer NOT NULL,
    status character varying(8) NOT NULL,
    PRIMARY KEY (id_group, id_account)
);

COMMENT ON TABLE public.join_request
    IS 'List of users, who have requested to join the group';

-- Favorites store TMDB identifiers directly instead of local movie ids.
-- media_type is required because movie and TV ids can overlap in TMDB.
DROP TABLE IF EXISTS public.favourite_movies;

CREATE TABLE IF NOT EXISTS public.favourite_movies
(
    id_account integer NOT NULL,
    tmdb_id integer NOT NULL,
    media_type character varying(5) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT favourite_movies_pk
        PRIMARY KEY (id_account, tmdb_id, media_type),

    CONSTRAINT favourite_movies_media_type_check
        CHECK (media_type IN ('movie', 'tv')),

    CONSTRAINT favourite_movies_account_fk
        FOREIGN KEY (id_account)
        REFERENCES public.account (id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

COMMENT ON TABLE public.favourite_movies
    IS 'Stores users favourite TMDB movies and TV shows.';

ALTER TABLE IF EXISTS public.favourite_movies
    ADD FOREIGN KEY (id_account)
    REFERENCES public.account (id)
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

DROP TABLE IF EXISTS public.movie;

CREATE TABLE IF NOT EXISTS public.movie
(
    id serial NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    duration interval NOT NULL,
    genre character varying(255)[] NOT NULL,
    release_date date,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.review;

CREATE TABLE IF NOT EXISTS public.review
(
    id_account integer NOT NULL,
    id_movie integer NOT NULL,
    rating smallint NOT NULL,
    description character varying(512) NOT NULL,
    date timestamp with time zone NOT NULL,
    PRIMARY KEY (id_account, id_movie)
);

ALTER TABLE IF EXISTS public."group"
    ADD FOREIGN KEY (id_owner)
    REFERENCES public.account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.member_list
    ADD FOREIGN KEY (id_group)
    REFERENCES public."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.member_list
    ADD FOREIGN KEY (id_account)
    REFERENCES public.account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.join_request
    ADD FOREIGN KEY (id_group)
    REFERENCES public."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.join_request
    ADD FOREIGN KEY (id_account)
    REFERENCES public.account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;



ALTER TABLE IF EXISTS public.review
    ADD FOREIGN KEY (id_account)
    REFERENCES public.account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.review
    ADD FOREIGN KEY (id_movie)
	REFERENCES public.movie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

END;
